### root api
GET http://localhost:8000/

### fetch all the tasks
GET http://localhost:8000/api/v1/task

### post the task
POST http://localhost:8000/api/v1/task
Content-Type: application/json

{
    "task": "Coding",
    "hr": 30,
    "id": 12
}

###  update or switch  task
PATCH http://localhost:8000/api/v1/task
Content-Type: application/json

{
    "_id": "62ed21c71f9df97024a808b6",
    "type": "bad"
}

###  deleted the tasks
DELETE http://localhost:8000/api/v1/task/
Content-Type: application/json

{
    "ids" : [
       "62ed179aa9c21598802c9616"
    ]
}
