### root api
GET http://localhost:8000/

### fetch all the tasks
GET http://localhost:8000/api/v1/task

### post the task
POST http://localhost:8000/api/v1/task
Content-Type: application/json

{
    "task": "Watching tv",
    "hr": 12,
    "id": 12
}

###  update or switch  task
PATCH http://localhost:8000/api/v1/task
Content-Type: application/json

{
    "_id": "62cebcbf0ede3b417cc23426",
    "type": "bad"
}

###  deleted the tasks
DELETE http://localhost:8000/api/v1/task/
Content-Type: application/json

{
    "_id" : 10
}
